name: CI

on: [push, pull_request]

jobs:
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.release_created }}

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release-please.outputs.release_created }}

      - run: pnpm i
        if: ${{ steps.release-please.outputs.release_created }}

      - run: pnpm build:packages
        if: ${{ steps.release-please.outputs.release_created }}

      - run: pnpm publish:packages
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: pnpm build:packages

      - run: pnpm publish:packages:commit
