name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: pnpm dlx pkg-pr-new publish --pnpm './packages/*'
